version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: continuumio/miniconda3

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            conda update -n base -c defaults conda            
            conda env create -f environment.yml
            source activate esci451
      # run tests!
      - run:
          name: run tests
          command: |
            source activate esci451
            pytest --nbval
      - store_artifacts:
          path: test-reports
          destination: test-reports

workflows:
  main:
    jobs:
      - build
