name: test
on:
  push:
    branches:
      - master
    pull_request:

jobs:
  test_code:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8]
      fail-fast: false

    steps:
      - uses: actions/checkout@v1

      - name: Setup conda
        uses: actions/cache@v1
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}
      - uses: goanpeca/setup-miniconda@v1
        with:
          miniconda-version: 'latest'
          python-version: ${{ matrix.python-version }}
          activate-environment: esci451
          environment-file: environment.yml
          condarc-file: .github/test_condarc.yml
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!

      - name: run test suite
        shell: bash -l {0}
        run: pytest --nbval
