name: test
on:
  push:
    branches:
      - master
    pull_request:

jobs:
  test_code:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: 'latest'
          python-version: ${{ matrix.python-version }}
          activate-environment: esci451
          environment-file: environment.yml
          condarc-file: .github/test_condarc.yml

      - name: run test suite
        shell: bash -l {0}
        run: pytest --nbval
